### PR TITLE
Fix alpha premultiplication

### LINKED ISSUE #4: Integral `premultiply*` and `unpremultiply*` functions are implemented incorrectly
I just tested your library and found that `premultiply_rgba8`, `unpremultiply_rgba8`, and similar are implemented incorrectly as of v0.1.5. This affects the methods for `u8` and `u16` of all color types and bit depths.

They all have the same bugs, so I will explain it using 8-bit RGBA: `premultiply_rgba8` squares the alpha channel, which is [not how premultiplied alpha works](https://learn.microsoft.com/en-us/windows/apps/develop/win2d/premultiplied-alpha). This bug is very obvious in the source code:

```rs
pub fn premultiply_rgba8(in_place: &mut [u8]) {
    for chunk in in_place.chunks_exact_mut(4) {
        let a = chunk[3] as u16;
        chunk[0] = div_by_255(chunk[0] as u16 * a);
        chunk[1] = div_by_255(chunk[1] as u16 * a);
        chunk[2] = div_by_255(chunk[2] as u16 * a);
        chunk[3] = div_by_255(a * a);
    }
}
```

The corresponding `unpremultiply*` methods of this library also do not account for squarred alpha. For example, see `unpremultiply_rgba8`:

```rs
pub fn unpremultiply_rgba8(in_place: &mut [u8]) {
    for chunk in in_place.chunks_exact_mut(4) {
        let a = chunk[3];
        if a != 0 {
            let a_recip = 1. / a as f32;
            chunk[0] = ((chunk[0] as f32 * 255.) * a_recip) as u8;
            chunk[1] = ((chunk[1] as f32 * 255.) * a_recip) as u8;
            chunk[2] = ((chunk[2] as f32 * 255.) * a_recip) as u8;
            chunk[3] = ((a as f32 * 255.) * a_recip) as u8;
        }
    }
}
```

Note that the color channels are not unpremultiplied correctly, because `a_recip` is computed from squarred alpha. Also note that `chunk[3] = ((a as f32 * 255.) * a_recip) as u8` makes absolutely no sense, because it's equivalent to `chunk[3] = 255`.

Putting both together, this means that the following code:

```rs
premultiply_rgba8(image);
unpremultiply_rgba8(image);
```

has the effect of `(R,G,B,A) -> (R/A, G/A, B/A, 1)` when it shouldn't change the image at all (within the bounds of the information that can be stored).

---

[The floating point methods](https://github.com/awxkee/pic-scale-safe/blob/a57e9d901c65ef4c49c6332c2acdd42bec7564d3/src/alpha.rs#L446-L558) are implemented correctly and don't have these issues.

### PR DESCRIPTION
**Pull request by awxkee**
Partically fixes #4

### CODE REVIEW

File: src/alpha.rs [hunk 1]
```diff
@@ -45,10 +61,9 @@ pub fn premultiply_rgba8(in_place: &mut [u8]) {
     // So everywhere is just added something beautiful.
     for chunk in in_place.chunks_exact_mut(4) {
         let a = chunk[3] as u16;
-        chunk[0] = div_by_255(chunk[0] as u16 * a);
-        chunk[1] = div_by_255(chunk[1] as u16 * a);
-        chunk[2] = div_by_255(chunk[2] as u16 * a);
-        chunk[3] = div_by_255(a * a);
+        chunk[0] = UNPREMULTIPLICATION_TABLE[(a + chunk[0] as u16) as usize];
```
Comment (RunDevelopment) [inline src/alpha.rs:64]: You used the UN-premultiplication table in the premultiply functions...

And you forgot to do a * 255.

Comment (awxkee) [reply src/alpha.rs:64]: Uhh. Thanks for notice.
